const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"贷款类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryDaikuan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"开户地管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKaihudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"理财产品类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryLicaicanpin"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"贷款管理",
                        "menuJump":"列表",
                        "tableName":"daikuan"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"贷款购买管理",
                        "menuJump":"列表",
                        "tableName":"daikuanGoumai"
                    }
                ],
                "menu":"贷款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"理财产品管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpin"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"理财产品购买管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpinGoumai"
                    }
                ],
                "menu":"理财产品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"审核人员管理",
                        "menuJump":"列表",
                        "tableName":"shenherenyuan"
                    }
                ],
                "menu":"审核人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"业务人员管理",
                        "menuJump":"列表",
                        "tableName":"yewurenyuan"
                    }
                ],
                "menu":"业务人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"银行卡管理",
                        "menuJump":"列表",
                        "tableName":"yinhangka"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"银行卡金额记录管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaJinejilu"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"银行卡补办管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkabuban"
                    }
                ],
                "menu":"银行卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"存款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuecunkuan"
                    }
                ],
                "menu":"存款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"取款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuequkuan"
                    }
                ],
                "menu":"取款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"转账管理",
                        "menuJump":"列表",
                        "tableName":"zhuanzhang"
                    }
                ],
                "menu":"转账管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"账户注销管理",
                        "menuJump":"列表",
                        "tableName":"zhanghuzhuxiao"
                    }
                ],
                "menu":"账户注销管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"贷款管理",
                        "menuJump":"列表",
                        "tableName":"daikuan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"贷款购买管理",
                        "menuJump":"列表",
                        "tableName":"daikuanGoumai"
                    }
                ],
                "menu":"贷款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"理财产品管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"理财产品购买管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpinGoumai"
                    }
                ],
                "menu":"理财产品管理"
            }
            ,{
                "child":[
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"银行卡补办管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkabuban"
                    }
                ],
                "menu":"银行卡补办管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"存款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuecunkuan"
                    }
                ],
                "menu":"存款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"取款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuequkuan"
                    }
                ],
                "menu":"取款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"转账管理",
                        "menuJump":"列表",
                        "tableName":"zhuanzhang"
                    }
                ],
                "menu":"转账管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"账户注销管理",
                        "menuJump":"列表",
                        "tableName":"zhanghuzhuxiao"
                    }
                ],
                "menu":"账户注销管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"审核人员",
        "tableName":"shenherenyuan"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"贷款管理",
                        "menuJump":"列表",
                        "tableName":"daikuan"
                    }
                ],
                "menu":"贷款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"理财产品管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpin"
                    }
                ],
                "menu":"理财产品管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"业务人员",
        "tableName":"yewurenyuan"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"贷款管理",
                        "menuJump":"列表",
                        "tableName":"daikuan"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"贷款购买管理",
                        "menuJump":"列表",
                        "tableName":"daikuanGoumai"
                    }
                ],
                "menu":"贷款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"理财产品管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpin"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"理财产品购买管理",
                        "menuJump":"列表",
                        "tableName":"licaicanpinGoumai"
                    }
                ],
                "menu":"理财产品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"银行卡管理",
                        "menuJump":"列表",
                        "tableName":"yinhangka"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"银行卡金额记录管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkaJinejilu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"银行卡补办管理",
                        "menuJump":"列表",
                        "tableName":"yinhangkabuban"
                    }
                ],
                "menu":"银行卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"存款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuecunkuan"
                    }
                ],
                "menu":"存款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"取款管理",
                        "menuJump":"列表",
                        "tableName":"yuyuequkuan"
                    }
                ],
                "menu":"取款管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"转账管理",
                        "menuJump":"列表",
                        "tableName":"zhuanzhang"
                    }
                ],
                "menu":"转账管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"账户注销管理",
                        "menuJump":"列表",
                        "tableName":"zhanghuzhuxiao"
                    }
                ],
                "menu":"账户注销管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
